@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class t_link_network_stats {
   full_short_url  /* 完整短链接 */: varchar(128)
   gid  /* 分组标识 */: varchar(32)
   date  /* 日期 */: date
   cnt  /* 访问量 */: int
   network  /* 访问网络 */: varchar(64)
   create_time  /* 创建时间 */: datetime
   update_time  /* 修改时间 */: datetime
   del_flag  /* 删除标识 0：未删除 1：已删除 */: tinyint(1)
   id  /* ID */: bigint
}

@enduml
