server:
  port: 8002

spring:
  application:
    name: admin-service # server name
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.232.131:8848 # nacos docker addr
      config:
        server-addr: 192.168.232.131:8848 # nacos docker addr
    feign:
      httpclient:
        enabled: true # 解决GET变POST的bug
#  datasource:
#    username: root
#    password: miirso
#    url: jdbc:mysql://192.168.232.131:3306/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-test-query: select 1
#      connection-timeout: 20000
#      idle-timeout: 300000
#      maximum-pool-size: 5
#      minimum-idle: 5
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yml
  data:
    redis:
      host: 192.168.232.131
      port: 6379
      password: miirso
      database: 15
